### ISSUE TITLE
ImageServers require a exportImage suffix, not export

### ISSUE THREAD

**Issue by iandees** [JasonSanford/tileify-ags#2]
I'm trying to support AGS "ImageServer" URLs like this one:

https://maps.co.ramsey.mn.us/arcgis/rest/services/OrthoPhotos/Aerial2018/ImageServer

It does not support the MapServer's `/export` suffix and requires `/exportImage` instead. For example this URL 400's:

```
https://maps.co.ramsey.mn.us/arcgis/rest/services/OrthoPhotos/Aerial2018/ImageServer/export?&bbox=-93.1695556640625%2C44.949249266611524%2C-93.16680908203125%2C44.95119307998577&bboxSR=4326&imageSR=3857&f=image&size=256%2C256
```

but this one works fine:

```
https://maps.co.ramsey.mn.us/arcgis/rest/services/OrthoPhotos/Aerial2018/ImageServer/exportImage?&bbox=-93.1695556640625%2C44.949249266611524%2C-93.16680908203125%2C44.95119307998577&bboxSR=4326&imageSR=3857&f=image&size=256%2C256
```

I can submit a PR to do a simple string check on the URL.

**Comment by JasonSanford** [comment]
Addressed in #3.
